export const browserCoreExamples = [
  "klaw browser status",
  "klaw browser start",
  "klaw browser stop",
  "klaw browser tabs",
  "klaw browser open https://example.com",
  "klaw browser focus abcd1234",
  "klaw browser close abcd1234",
  "klaw browser screenshot",
  "klaw browser screenshot --full-page",
  "klaw browser screenshot --ref 12",
  "klaw browser snapshot",
  "klaw browser snapshot --format aria --limit 200",
  "klaw browser snapshot --efficient",
  "klaw browser snapshot --labels",
];

export const browserActionExamples = [
  "klaw browser navigate https://example.com",
  "klaw browser resize 1280 720",
  "klaw browser click 12 --double",
  'openclaw browser type 23 "hello" --submit',
  "klaw browser press Enter",
  "klaw browser hover 44",
  "klaw browser drag 10 11",
  "klaw browser select 9 OptionA OptionB",
  "klaw browser upload /tmp/openclaw/uploads/file.pdf",
  'openclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "klaw browser dialog --accept",
  'openclaw browser wait --text "Done"',
  "klaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "klaw browser console --level error",
  "klaw browser pdf",
];
